#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
pwsh "$SCRIPT_DIR/../pre-commit.ps1" # We simply wrap the pre-commit.ps1
