on:
  push:

jobs:
  CI:
    name: Build project
    runs-on: [self-hosted, Windows, x64, TwinCAT]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build and run tests
        shell: pwsh
        run: |
          whoami
          .\build.ps1 -Configuration Release
          dotnet test --configuration Release --no-build --logger "console;verbosity=detailed" .\TwinGet.sln
