on:
  push:

jobs:
  CI:
    name: Build project
    runs-on: [self-hosted, Windows, x64, TwinCAT]
    steps:
      - uses: actions/checkout@v3
      - run: .\build.ps1 -Configuration Release
      - run: dotnet test --configuration Release --no-build --logger "console;verbosity=detailed" .\TwinGet.sln
