on:
  push:

jobs:
  CI:
    name: Build project
    runs-on: [self-hosted, Windows, x64, TwinCAT]
    permissions: 
      checks: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build
        shell: pwsh
        run: |
          .\build.ps1 -Configuration Release

      - name: Run tests
        shell: pwsh
        run: |
          dotnet test --configuration Release --no-build --logger "trx;verbosity=detailed;LogFileName=test_results.trx" .\TwinGet.sln

      - name: Test results reporting
        if: success() || failure() 
        uses: dorny/test-reporter@v1
        with:
          name: xUnit tests
          path: ./test/*/TestResults/*.trx
          reporter: dotnet-trx
