on:
  push:

jobs:
  CI:
    name: Build project
    runs-on: [self-hosted, Windows, x64, TwinCAT]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - run: .\build.ps1
      - run: dotnet test --no-build .\TwinGet.sln
